### PR TITLE
Add option to use helm plugins

### PR DESCRIPTION
**Pull request by scottcrossen**
Also use latest version of helmfile (Should I seperate this into two PRs? Probably. Let me know)

### CODE REVIEW

**Comment by travisghansen** [comment]
Thanks for the contribution! I’m happy to incorporate these changes generally but will have a little feedback when I have a little extra time. Shouldn’t take long maybe in the next day or 2.

The helmfile binary situation is trickier than it seems. I for sure want to pin specific versions and I’ll have to check if both curl and wget are in the default images. It seems at some point curl was removed but maybe it’s been readded.

**Comment by scottcrossen** [comment]
Oh. I did not realize I used curl. It is not default and I didn't test that branch. I can remove the helmfile version changes and keep this just a PR for the helm plugin stuff. I only work on weekends so plz be patient :)

**Comment by scottcrossen** [comment]
There. I changed some files. That should be much cleaner.

**Comment by scottcrossen** [comment]
I've tested this on helm3 and it works great with the plugin helm-secrets

**Comment by travisghansen** [comment]
Ok I’ll look at this today and test. I need to think through the security implications.

**Comment by travisghansen** [comment]
OK, some initial thoughts..

- `helmfile` itself does allow arbitrary `exec` calls which means most of the security implications are irrelevant
- the approach of the MR seems less than ideal for a couple immediate reasons
  - while technically possible to dig up versioned URLs, it probably easier for most folks to use the `--version` flag with `helm plugin ...` than dig up version specific URLs
  - re-installing/downloading the plugins each time a reconciliation is done seems pretty inefficient
- for folks who know what plugins/versions they use, it's probably best to download those plugins using the pod startup process (so it's only done once, etc)

My proposal is the following:

- Run `$HELM_PLUGINS` through the variable expansion process (so the path of the plugin dir can be more easily predicted and/or shared) which will make it easier to use plugins installed during pod startup.
- introduce a new feature/env var that allow *any* arbitrary script to execute during the init phase (likely as stored in the git repo itself: ie, sit next to the `helmfile.yaml`)

With the above 2, it should be easier/more efficient to handle this use-case and many more.

Any thoughts? I'm going to start digging in.

**Comment by travisghansen** [comment]
Implemented necessary bits to support plugins here: https://github.com/travisghansen/argo-cd-helmfile/commit/0bff2e3f07ac967f33649608ff42f95326639ee4

**Comment by scottcrossen** [comment]
I like your reasoning! Pulling plugins each time is pretty annoying. Plus, I learned that my proposal PR added some ignored error messages which clutters the logs. In the case of `helm secrets`, developers already have to install sops and any credentials separately so installing plugins separately makes sense!

**Comment by travisghansen** [comment]
Try it out and let me know how it goes!

**Pull request closed without merging**
